amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials[:aws][:write][:access_key_id] %>
  secret_access_key: <%= Rails.application.credentials[:aws][:write][:secret_access_key] %>
  region: us-east-2
  bucket: pbogardcom-files