class Map
  include ActionView::Helpers
  
  def draw
        
    html = %Q(<div class="center">)
    html += link_to(image_tag(Rails.application.routes.url_helpers.gcmap_image_path(airport_options, query.gsub("/","_"), Map.hash_image_query(query)), :alt => alt_tag, :class => "map"), "http://www.gcmap.com/mapui?PM=#{airport_options}&MP=r&MS=wls2&P=#{query}", target: "_blank")
    html += %Q(<div class="credit map-credit">Map generated by #{link_to("Great Circle Mapper", "http://www.gcmap.com/", target: "_blank")}</div>)
    html += "</div>\n"
    
    
    return html.html_safe
    
  end

  # Returns a SafeBuffer containing HTML for a Great Circle Mapper map.
  def gcmap
    return airport_details
  end

  # Returns a SafeBuffer contining XML data for a GPX file.
  def gpx

  end

  # Returns a SafeBuffer containing XML data for a KML file.
  def kml

  end
  
  def exists?
    query.present?
  end
  
  # Returns an array of IATA codes representing all airports used on this map.
  def used_airports
    used_from_airports = airports_inside_region | airports_outside_region | airports_highlighted | airports_frequency
    used_from_routes = (routes_inside_region | routes_outside_region | routes_highlighted | routes_unhighlighted).map{|r| r.split(/[-\/]/)}.flatten
    return (used_from_airports | used_from_routes).uniq.sort
  end
  
  # Return a hash of a map query based on a secret key
  # Params: 
  # +query+:: The query to hash
  def self.hash_image_query(query)
    Digest::MD5.hexdigest(query + ENV["IMAGE_KEY"])
  end
  
  private

    # Returns a hash of airport details in the form of {airport_id => {latitude: 0, longitude: 0, city: "City", country: "Country", iata: "AAA", icao: "AAAA"}}
    def airport_details
      details = Hash.new

      airport_ids = Array.new
      airport_ids |= airports_normal
      airport_ids |= airports_highlighted
      airport_ids |= airports_out_of_region
      airport_ids |= routes_normal.flatten
      airport_ids |= routes_highlighted.flatten
      airport_ids |= routes_out_of_region.flatten
      airport_ids = airport_ids.uniq.sort

      airports = Airport.where(id: airport_ids)
      airports.each do |airport|
        details[airport.id] = {iata: airport.iata_code, icao: airport.icao_code, latitude: airport.latitude, longitude: airport.longitude, city: airport.city, country: airport.country, visits: airport_frequencies[airport.id]}
      end

      return details
    end

    # Returns an array of airport IDs
    def airports_normal
      return Array.new
    end

    # Returns an array of airport IDs
    def airports_highlighted
      return Array.new
    end

    # Returns an array of airport IDs
    def airports_out_of_region
      return Array.new
    end

    # Returns a hash of airport frequencies in the form of {airport_id => frequency}
    def airport_frequencies
      return Hash.new
    end

    # Returns an array of routes in the form of [[airport_1_id, airport_2_id]]. The IDs should be sorted.
    def routes_normal
      return Array.new
    end

    # Returns an array of routes in the form of [[airport_1_id, airport_2_id]]. The IDs should be sorted.
    def routes_highlighted
      return Array.new
    end

    # Returns an array of routes in the form of [[airport_1_id, airport_2_id]]. The IDs should be sorted.
    def routes_out_of_region
      return Array.new
    end

    # Returns a hash of route frequencies in the form of {[airport_1_id, airport_2_id] => frequency}
    def route_frequencies
      return Hash.new
    end

    # Old methods:
  
    def airport_options
      return "b:disc5:black"
    end
    
    def alt_tag
      return "Map of flight routes"
    end
      
    def routes_inside_region
      return Array.new
    end
  
    def routes_outside_region
      return Array.new
    end
  
    def routes_highlighted
      return Array.new
    end
    
    def routes_unhighlighted
      return Array.new
    end
  
    def airports_inside_region
      return Array.new
    end
    
    def airports_outside_region
      return Array.new
    end
  
    def airports_highlighted
      return Array.new
    end
    
    def airports_frequency
      return Array.new
    end
  
    def query
      query_sections = Array.new
      
      if routes_outside_region.any? || routes_unhighlighted.any?
        
        query_sections.push("c:%23FF7777")
        
        # Add routes outside region:
        if routes_outside_region.any?
          query_sections.push("o:noext")
          query_sections.push(routes_outside_region.join(",o:noext,"))
        end
      
        # Add unhighlighted routes:
        if routes_unhighlighted.any?
          query_sections.push(routes_unhighlighted.join(","))
        end
        
      end
      
      if routes_inside_region.any? || routes_highlighted.any?
        
        query_sections.push("c:red")
        
        # Add routes inside region:
        if routes_inside_region.any?
          query_sections.push(routes_inside_region.join(","))
        end
      
        # Add highlighted routes:
        if routes_highlighted.any?
          query_sections.push("w:2")
          query_sections.push(routes_highlighted.join(","))
        end
      
      end
      
      # Add airports:
      if airports_inside_region.any?
        query_sections.push(airports_inside_region.join(","))
      end
      
      # Add highlighted airports:
      if airports_highlighted.any?
        if @include_names
          query_sections.push(%Q(m:p:ring11:black%2B"%25N"12r%3A%23666))
        else
          query_sections.push("m:p:ring11:black")
        end
        query_sections.push(airports_highlighted)
      end
      
      # Add frequency rings:
      if airports_frequency.any?
        query_sections.push(airports_frequency.join(","))
      end
      
      if query_sections.length > 0
        return query_sections.join(",")
      else
        return " "
      end
    end
    
    # Convert a set of pairs into a Great Circle Mapper formatted querystring, minimizing string length.
    # Params:
    # +pairs+:: An array of arrays of two IATA codes.
    def compressed_routes(pairs)
      routes = Array.new
      pairs = pairs.uniq.sort_by{|k| [k[0],k[1]]}
      previous_origin = nil
      route_string = nil
      pairs.each do |pair|
        if pair[0] == previous_origin && route_string
          route_string += "/#{pair[1]}"
        else
          routes.push(route_string) if route_string
          route_string = "#{pair[0]}-#{pair[1]}"
        end
        routes.push(route_string) if (pair == pairs.last && route_string)
        previous_origin = pair[0]
      end
      return routes
    end
  
end